/**
 * Demo Buyers Data for Admin Dashboard
 * Used as fallback when Airtable API is unavailable
 */

import { TransformedBuyer } from "@/hooks/useAirtableData";

const today = new Date();
const daysAgo = (days: number) => new Date(today.getTime() - days * 24 * 60 * 60 * 1000).toISOString();

export const demoBuyers: TransformedBuyer[] = [
  {
    id: "demo-1",
    leadId: 1001,
    name: "James Richardson",
    firstName: "James",
    lastName: "Richardson",
    email: "james.richardson@gmail.com",
    phone: "+44 7700 900123",
    budgetRange: "£800k - £1.2M",
    bedrooms: "3",
    location: "Canary Wharf",
    country: "United Kingdom",
    timeline: "0 - 3 months",
    paymentMethod: "Cash",
    purpose: "Investment",
    score: 92,
    intent: "Hot",
    status: "Viewing Booked",
    assignedCaller: "Sarah Johnson",
    preferredComm: "WhatsApp",
    summary: "Serious investor looking for 3-bed in Canary Wharf. Prefers new builds with river views. Ready to move quickly with cash purchase.",
    development: "Royal Wharf",
    createdTime: daysAgo(2),
    agentTranscription: "Client confirmed budget and timeline. Very interested in new launches.",
    linkedinProfile: "https://linkedin.com/in/jamesrichardson",
    purchaseIn28Days: true,
    brokerNeeded: false,
    campaignName: "Royal Wharf Q1",
    source: "Meta Campaign",
    notes: "VIP lead - prioritize",
    rawFields: {},
  },
  {
    id: "demo-2",
    leadId: 1002,
    name: "Emma Thompson",
    firstName: "Emma",
    lastName: "Thompson",
    email: "emma.t@outlook.com",
    phone: "+44 7700 900456",
    budgetRange: "£500k - £700k",
    bedrooms: "2",
    location: "Greenwich",
    country: "United Kingdom",
    timeline: "3 - 6 months",
    paymentMethod: "Mortgage",
    purpose: "Primary Residence",
    score: 78,
    intent: "Warm",
    status: "Contacted - In Progress",
    assignedCaller: "Michael Chen",
    preferredComm: "Email",
    summary: "First-time buyer looking for 2-bed apartment in South East London. Pre-approved for mortgage.",
    development: "Greenwich Peninsula",
    createdTime: daysAgo(5),
    agentTranscription: "Good call. Client needs 2 months to finalize mortgage.",
    linkedinProfile: "",
    purchaseIn28Days: false,
    brokerNeeded: true,
    campaignName: "Greenwich Q1",
    source: "Instagram",
    notes: "",
    rawFields: {},
  },
  {
    id: "demo-3",
    leadId: 1003,
    name: "Ahmed Al-Rashid",
    firstName: "Ahmed",
    lastName: "Al-Rashid",
    email: "ahmed.alrashid@company.ae",
    phone: "+971 50 123 4567",
    budgetRange: "£2M - £3M",
    bedrooms: "4",
    location: "Mayfair",
    country: "United Arab Emirates",
    timeline: "0 - 3 months",
    paymentMethod: "Cash",
    purpose: "Investment",
    score: 95,
    intent: "Hot",
    status: "Offer Made",
    assignedCaller: "Sarah Johnson",
    preferredComm: "WhatsApp",
    summary: "International investor from Dubai. Looking for luxury 4-bed for portfolio. Multiple property owner.",
    development: "One Nine Elms",
    createdTime: daysAgo(1),
    agentTranscription: "Client ready to proceed. Requesting floor plans for penthouse units.",
    linkedinProfile: "https://linkedin.com/in/ahmedalrashid",
    purchaseIn28Days: true,
    brokerNeeded: false,
    campaignName: "International Luxury",
    source: "Google Ads",
    notes: "High priority - international buyer",
    rawFields: {},
  },
  {
    id: "demo-4",
    leadId: 1004,
    name: "Sophie Williams",
    firstName: "Sophie",
    lastName: "Williams",
    email: "sophie.williams@mail.com",
    phone: "+44 7700 900789",
    budgetRange: "£350k - £450k",
    bedrooms: "1",
    location: "Wembley",
    country: "United Kingdom",
    timeline: "6 - 9 months",
    paymentMethod: "Help to Buy",
    purpose: "Primary Residence",
    score: 65,
    intent: "Warm",
    status: "Follow Up",
    assignedCaller: "",
    preferredComm: "Phone",
    summary: "Young professional looking for first property. Interested in Help to Buy scheme.",
    development: "Wembley Park",
    createdTime: daysAgo(8),
    agentTranscription: "",
    linkedinProfile: "",
    purchaseIn28Days: false,
    brokerNeeded: true,
    campaignName: "First Time Buyers",
    source: "Facebook",
    notes: "Needs to save for deposit",
    rawFields: {},
  },
  {
    id: "demo-5",
    leadId: 1005,
    name: "David Chen",
    firstName: "David",
    lastName: "Chen",
    email: "david.chen@techcorp.hk",
    phone: "+852 9123 4567",
    budgetRange: "£1.5M - £2M",
    bedrooms: "3",
    location: "Battersea",
    country: "Hong Kong",
    timeline: "0 - 3 months",
    paymentMethod: "Cash",
    purpose: "Investment",
    score: 88,
    intent: "Hot",
    status: "Viewing Booked",
    assignedCaller: "Michael Chen",
    preferredComm: "WeChat",
    summary: "Hong Kong investor looking for London pied-à-terre. Also interested for children's education.",
    development: "Battersea Power Station",
    createdTime: daysAgo(3),
    agentTranscription: "Virtual viewing completed. Client flying to London next month.",
    linkedinProfile: "https://linkedin.com/in/davidchen",
    purchaseIn28Days: true,
    brokerNeeded: false,
    campaignName: "Hong Kong Campaign",
    source: "WeChat Ads",
    notes: "",
    rawFields: {},
  },
  {
    id: "demo-6",
    leadId: 1006,
    name: "Rachel Green",
    firstName: "Rachel",
    lastName: "Green",
    email: "rachel.green@email.co.uk",
    phone: "+44 7700 900321",
    budgetRange: "£600k - £800k",
    bedrooms: "2",
    location: "Kings Cross",
    country: "United Kingdom",
    timeline: "3 - 6 months",
    paymentMethod: "Mortgage",
    purpose: "Primary Residence",
    score: 72,
    intent: "Warm",
    status: "Contacted - In Progress",
    assignedCaller: "Sarah Johnson",
    preferredComm: "Email",
    summary: "Professional couple looking to upgrade from rented flat. Work in central London.",
    development: "Argent Related",
    createdTime: daysAgo(6),
    agentTranscription: "Scheduled second call for next week.",
    linkedinProfile: "",
    purchaseIn28Days: false,
    brokerNeeded: true,
    campaignName: "Kings Cross Q1",
    source: "Meta Campaign",
    notes: "",
    rawFields: {},
  },
  {
    id: "demo-7",
    leadId: 1007,
    name: "Marcus Johnson",
    firstName: "Marcus",
    lastName: "Johnson",
    email: "marcus.j@business.com",
    phone: "+44 7700 900654",
    budgetRange: "£1M - £1.5M",
    bedrooms: "3",
    location: "Islington",
    country: "United Kingdom",
    timeline: "0 - 3 months",
    paymentMethod: "Cash",
    purpose: "Primary Residence",
    score: 85,
    intent: "Hot",
    status: "Viewing Booked",
    assignedCaller: "Michael Chen",
    preferredComm: "Phone",
    summary: "Selling current property and looking to buy in North London. Chain-free buyer.",
    development: "City North",
    createdTime: daysAgo(4),
    agentTranscription: "Client confirmed chain-free. Viewing scheduled for Saturday.",
    linkedinProfile: "https://linkedin.com/in/marcusjohnson",
    purchaseIn28Days: true,
    brokerNeeded: false,
    campaignName: "North London",
    source: "Google Ads",
    notes: "",
    rawFields: {},
  },
  {
    id: "demo-8",
    leadId: 1008,
    name: "Fatima Hassan",
    firstName: "Fatima",
    lastName: "Hassan",
    email: "fatima.hassan@email.com",
    phone: "+44 7700 900987",
    budgetRange: "£400k - £550k",
    bedrooms: "2",
    location: "Stratford",
    country: "United Kingdom",
    timeline: "6 - 9 months",
    paymentMethod: "Mortgage",
    purpose: "Investment",
    score: 58,
    intent: "Cold",
    status: "No Response",
    assignedCaller: "",
    preferredComm: "Email",
    summary: "Buy-to-let investor interested in East London developments.",
    development: "Stratford Central",
    createdTime: daysAgo(12),
    agentTranscription: "",
    linkedinProfile: "",
    purchaseIn28Days: false,
    brokerNeeded: true,
    campaignName: "BTL Investors",
    source: "LinkedIn",
    notes: "Multiple contact attempts - no response",
    rawFields: {},
  },
  {
    id: "demo-9",
    leadId: 1009,
    name: "Oliver Wright",
    firstName: "Oliver",
    lastName: "Wright",
    email: "oliver.wright@mail.com",
    phone: "+44 7700 900147",
    budgetRange: "£700k - £900k",
    bedrooms: "2",
    location: "Shoreditch",
    country: "United Kingdom",
    timeline: "0 - 3 months",
    paymentMethod: "Cash",
    purpose: "Primary Residence",
    score: 82,
    intent: "Hot",
    status: "Interested",
    assignedCaller: "Sarah Johnson",
    preferredComm: "WhatsApp",
    summary: "Tech entrepreneur looking for modern apartment near Old Street.",
    development: "The Stage",
    createdTime: daysAgo(2),
    agentTranscription: "Very engaged. Requested brochure and pricing.",
    linkedinProfile: "https://linkedin.com/in/oliverwright",
    purchaseIn28Days: true,
    brokerNeeded: false,
    campaignName: "Tech Professionals",
    source: "Meta Campaign",
    notes: "",
    rawFields: {},
  },
  {
    id: "demo-10",
    leadId: 1010,
    name: "Lisa Chang",
    firstName: "Lisa",
    lastName: "Chang",
    email: "lisa.chang@invest.sg",
    phone: "+65 9876 5432",
    budgetRange: "£1.2M - £1.8M",
    bedrooms: "3",
    location: "Fulham",
    country: "Singapore",
    timeline: "3 - 6 months",
    paymentMethod: "Cash",
    purpose: "Investment",
    score: 76,
    intent: "Warm",
    status: "Follow Up",
    assignedCaller: "Michael Chen",
    preferredComm: "WhatsApp",
    summary: "Singapore-based investor expanding UK portfolio. Interested in SW London.",
    development: "Lillie Square",
    createdTime: daysAgo(7),
    agentTranscription: "Good initial call. Client comparing multiple developments.",
    linkedinProfile: "",
    purchaseIn28Days: false,
    brokerNeeded: false,
    campaignName: "Singapore Launch",
    source: "Partner Referral",
    notes: "",
    rawFields: {},
  },
  {
    id: "demo-11",
    leadId: 1011,
    name: "Tom Bradley",
    firstName: "Tom",
    lastName: "Bradley",
    email: "tom.bradley@corporate.com",
    phone: "+44 7700 900258",
    budgetRange: "£450k - £600k",
    bedrooms: "1",
    location: "Woolwich",
    country: "United Kingdom",
    timeline: "0 - 3 months",
    paymentMethod: "Mortgage",
    purpose: "Primary Residence",
    score: 70,
    intent: "Warm",
    status: "Contacted - In Progress",
    assignedCaller: "",
    preferredComm: "Phone",
    summary: "Working professional relocating to London. Need close to Elizabeth Line.",
    development: "Royal Arsenal",
    createdTime: daysAgo(4),
    agentTranscription: "",
    linkedinProfile: "",
    purchaseIn28Days: false,
    brokerNeeded: true,
    campaignName: "Woolwich Q1",
    source: "Facebook",
    notes: "Pre-approved mortgage in place",
    rawFields: {},
  },
  {
    id: "demo-12",
    leadId: 1012,
    name: "Priya Sharma",
    firstName: "Priya",
    lastName: "Sharma",
    email: "priya.sharma@email.in",
    phone: "+91 98765 43210",
    budgetRange: "£600k - £800k",
    bedrooms: "2",
    location: "Hounslow",
    country: "India",
    timeline: "6 - 9 months",
    paymentMethod: "Cash",
    purpose: "Investment",
    score: 64,
    intent: "Warm",
    status: "New",
    assignedCaller: "",
    preferredComm: "Email",
    summary: "NRI investor interested in West London properties for rental income.",
    development: "Hounslow Central",
    createdTime: daysAgo(1),
    agentTranscription: "",
    linkedinProfile: "https://linkedin.com/in/priyasharma",
    purchaseIn28Days: false,
    brokerNeeded: false,
    campaignName: "NRI Campaign",
    source: "Meta Campaign",
    notes: "New lead - needs initial contact",
    rawFields: {},
  },
];

// Get demo stats
export function getDemoBuyerStats() {
  const total = demoBuyers.length;
  const hot = demoBuyers.filter(b => b.intent === "Hot").length;
  const warm = demoBuyers.filter(b => b.intent === "Warm").length;
  const viewingsBooked = demoBuyers.filter(b => b.status.toLowerCase().includes("viewing")).length;
  const offers = demoBuyers.filter(b => b.status.toLowerCase().includes("offer")).length;
  
  return {
    total,
    hot,
    warm,
    viewingsBooked,
    offers,
    avgScore: Math.round(demoBuyers.reduce((sum, b) => sum + b.score, 0) / total),
  };
}
