import { User, Development, Campaign, Lead, DailyMetrics, Settings, LeadSource } from "./types";
import { classifyLead } from "./leadClassification";

// Generate dates for the last 14 days
const generateDates = (days: number): string[] => {
  const dates: string[] = [];
  for (let i = days - 1; i >= 0; i--) {
    const date = new Date();
    date.setDate(date.getDate() - i);
    dates.push(date.toISOString().split("T")[0]);
  }
  return dates;
};

// Demo Users
export const demoUsers: User[] = [
  {
    id: "user_dev_1",
    email: "developer@naybourhood.ai",
    name: "James Developer",
    role: "developer",
    createdAt: "2024-01-15T10:00:00Z",
  },
  {
    id: "user_agent_1",
    email: "agent@naybourhood.ai",
    name: "Sarah Agent",
    role: "agent",
    createdAt: "2024-02-10T10:00:00Z",
  },
  {
    id: "user_broker_1",
    email: "broker@naybourhood.ai",
    name: "Mike Broker",
    role: "broker",
    createdAt: "2024-03-05T10:00:00Z",
  },
];

// Demo Developments
export const demoDevelopments: Development[] = [
  {
    id: "dev_1",
    name: "Marina Heights",
    location: "London, Canary Wharf",
    region: "London",
    priceRange: "£450,000 - £1,200,000",
    units: 120,
    unitsSold: 45,
    status: "live",
    image: "🏢",
  },
  {
    id: "dev_2",
    name: "Skyline Tower",
    location: "Manchester, City Centre",
    region: "Manchester",
    priceRange: "£280,000 - £650,000",
    units: 85,
    unitsSold: 12,
    status: "pre-launch",
    image: "🏗️",
  },
  {
    id: "dev_3",
    name: "Riverside Plaza",
    location: "Birmingham, Jewellery Quarter",
    region: "Birmingham",
    priceRange: "£220,000 - £480,000",
    units: 200,
    unitsSold: 200,
    status: "sold-out",
    image: "✅",
  },
  {
    id: "dev_4",
    name: "Garden Residences",
    location: "Leeds, Headingley",
    region: "Leeds",
    priceRange: "£180,000 - £350,000",
    units: 64,
    unitsSold: 28,
    status: "live",
    image: "🌳",
  },
];

// Demo Campaigns
export const demoCampaigns: Campaign[] = [
  {
    id: "camp_1",
    name: "Marina Heights - Lagos HNWI",
    developmentId: "dev_1",
    developmentName: "Marina Heights",
    objective: "leads",
    status: "live",
    budget: 2500,
    dailyCap: 100,
    startDate: "2024-10-01",
    isOngoing: true,
    roleType: "developer",
    channel: "meta",
    createdAt: "2024-09-28T10:00:00Z",
    creatives: {
      assets: [
        { id: "asset_1", type: "static", url: "https://picsum.photos/seed/marina1/400/300" },
        { id: "asset_2", type: "static", url: "https://picsum.photos/seed/marina2/400/300" },
      ],
      images: [],
      selectedHeadline: "Invest in London's Premier Waterfront Living",
      selectedPrimaryText: "Discover Marina Heights - Luxury apartments with guaranteed rental yields. Perfect for international investors seeking stable UK property returns.",
      selectedCta: "Learn More",
      generatedHeadlines: [
        "Invest in London's Premier Waterfront Living",
        "Secure Your Future with UK Property",
        "Luxury Living Meets Smart Investment",
      ],
      generatedPrimaryTexts: [
        "Discover Marina Heights - Luxury apartments with guaranteed rental yields.",
        "Premium Canary Wharf location with world-class amenities.",
        "Join savvy investors securing UK property portfolios.",
      ],
      generatedCtas: ["Learn More", "Get Details", "Book Consultation"],
    },
    metaCampaignId: "meta_camp_12345",
    metaAdsetId: "meta_adset_67890",
    metaFormId: "meta_form_11111",
    metaAdIds: ["meta_ad_001", "meta_ad_002"],
  },
  {
    id: "camp_2",
    name: "Skyline Tower - UK Investors",
    developmentId: "dev_2",
    developmentName: "Skyline Tower",
    objective: "leads",
    status: "draft",
    budget: 1800,
    startDate: "2024-11-15",
    endDate: "2025-02-15",
    isOngoing: false,
    roleType: "developer",
    channel: "meta",
    createdAt: "2024-11-01T10:00:00Z",
  },
  {
    id: "camp_3",
    name: "Garden Residences - First Time Buyers",
    developmentId: "dev_4",
    developmentName: "Garden Residences",
    objective: "leads",
    status: "draft",
    budget: 1200,
    startDate: "2024-11-20",
    isOngoing: true,
    roleType: "agent",
    channel: "meta",
    createdAt: "2024-11-05T10:00:00Z",
  },
];

// Demo Leads with sources and classifications
const createLead = (
  id: string,
  name: string,
  email: string,
  phone: string,
  countryCode: string,
  country: string,
  budget: string,
  bedrooms: string,
  intentScore: number,
  qualityScore: number,
  status: Lead["status"],
  campaignId: string,
  campaignName: string,
  createdAt: string,
  notes: string,
  source: LeadSource,
  sourceDetail?: string,
  paymentMethod?: Lead["paymentMethod"],
  buyerStatus?: Lead["buyerStatus"],
  purchaseTimeline?: Lead["purchaseTimeline"],
  purpose?: Lead["purpose"],
  viewingScheduled?: string
): Lead => ({
  id,
  name,
  email,
  phone,
  countryCode,
  country,
  budget,
  bedrooms,
  intentScore,
  qualityScore,
  status,
  campaignId,
  campaignName,
  createdAt,
  notes,
  source,
  sourceDetail,
  paymentMethod,
  buyerStatus,
  purchaseTimeline,
  purpose,
  viewingScheduled,
  classification: classifyLead(intentScore, qualityScore),
});

export const demoLeads: Lead[] = [
  createLead(
    "lead_1",
    "James Okonkwo",
    "james.o@example.com",
    "+234 801 234 5678",
    "NG",
    "Nigeria",
    "£800,000 - £1,200,000",
    "3-4 bed",
    78,
    85,
    "contacted",
    "camp_1",
    "Marina Heights - Lagos HNWI",
    new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    "Interested in waterfront properties. Looking to relocate from Lagos.",
    "meta_campaign",
    undefined,
    "cash",
    "actively_looking",
    "0_3_months",
    "investment"
  ),
  createLead(
    "lead_2",
    "Sarah Mitchell",
    "sarah.m@example.com",
    "+44 7700 900123",
    "GB",
    "United Kingdom",
    "£500,000 - £750,000",
    "2 bed",
    91,
    72,
    "booked_viewing",
    "camp_1",
    "Marina Heights - Lagos HNWI",
    new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    "First-time buyer, very engaged.",
    "direct_web",
    "Website Contact Form",
    "mortgage",
    "actively_looking",
    "within_28_days",
    "primary_residence",
    new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString()
  ),
  createLead(
    "lead_3",
    "Ahmed Al-Rashid",
    "ahmed.r@example.com",
    "+971 50 123 4567",
    "AE",
    "UAE",
    "£1,500,000 - £2,000,000",
    "Penthouse",
    85,
    90,
    "offer",
    "camp_1",
    "Marina Heights - Lagos HNWI",
    new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
    "Made offer on Skyline Tower penthouse. Awaiting developer response.",
    "introducer",
    "Knight Frank Dubai",
    "cash",
    "actively_looking",
    "within_28_days",
    "investment"
  ),
  createLead(
    "lead_4",
    "Jennifer Wong",
    "jenny.w@example.com",
    "+65 9123 4567",
    "SG",
    "Singapore",
    "£600,000 - £900,000",
    "2-3 bed",
    82,
    68,
    "new",
    "camp_1",
    "Marina Heights - Lagos HNWI",
    new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    "Exploring investment opportunities in UK property market.",
    "portal",
    "Rightmove",
    "mortgage",
    "browsing",
    "3_6_months",
    "investment"
  ),
  createLead(
    "lead_5",
    "Marcus Thompson",
    "marcus.t@example.com",
    "+1 555 0123",
    "US",
    "USA",
    "£700,000 - £1,000,000",
    "3 bed house",
    76,
    79,
    "contacted",
    "camp_1",
    "Marina Heights - Lagos HNWI",
    new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    "Interested in areas with good schools. Family of 4.",
    "email_forward",
    "Forwarded from info@devco.com",
    "mortgage",
    "actively_looking",
    "0_3_months",
    "primary_residence"
  ),
  createLead(
    "lead_6",
    "Emma Richardson",
    "emma.r@example.com",
    "+44 7890 123456",
    "GB",
    "United Kingdom",
    "£350,000 - £450,000",
    "2 bed",
    65,
    72,
    "new",
    "camp_1",
    "Marina Heights - Lagos HNWI",
    new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(),
    "Young professional looking for first property.",
    "meta_campaign",
    undefined,
    "mortgage",
    "browsing",
    "6_9_months",
    "primary_residence"
  ),
  createLead(
    "lead_7",
    "David Chen",
    "david.c@example.com",
    "+852 9876 5432",
    "HK",
    "Hong Kong",
    "£900,000 - £1,300,000",
    "3 bed",
    88,
    84,
    "won",
    "camp_1",
    "Marina Heights - Lagos HNWI",
    new Date(Date.now() - 72 * 60 * 60 * 1000).toISOString(),
    "Completed purchase of Unit 405.",
    "crm_import",
    "Salesforce via Zapier",
    "cash",
    "actively_looking",
    "within_28_days",
    "investment"
  ),
  createLead(
    "lead_8",
    "Priya Sharma",
    "priya.s@example.com",
    "+91 98765 43210",
    "IN",
    "India",
    "£400,000 - £600,000",
    "2 bed",
    58,
    62,
    "lost",
    "camp_1",
    "Marina Heights - Lagos HNWI",
    new Date(Date.now() - 96 * 60 * 60 * 1000).toISOString(),
    "Budget constraints - decided to wait.",
    "manual_upload",
    "Event Leads CSV",
    "undecided",
    "browsing",
    "12_months_plus",
    "holiday_home"
  ),
  createLead(
    "lead_9",
    "Oliver Blackwood",
    "oliver.b@example.com",
    "+44 7555 123890",
    "GB",
    "United Kingdom",
    "£1,200,000 - £1,800,000",
    "4 bed",
    92,
    88,
    "booked_viewing",
    "camp_1",
    "Marina Heights - Lagos HNWI",
    new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
    "Downsizing from Surrey. Cash buyer. Very motivated.",
    "direct_web",
    "Landing Page",
    "cash",
    "actively_looking",
    "within_28_days",
    "primary_residence",
    new Date(Date.now() + 1 * 24 * 60 * 60 * 1000).toISOString()
  ),
  createLead(
    "lead_10",
    "Fatima Al-Hassan",
    "fatima.h@example.com",
    "+966 55 123 4567",
    "SA",
    "Saudi Arabia",
    "£2,000,000+",
    "Penthouse",
    45,
    92,
    "new",
    "camp_1",
    "Marina Heights - Lagos HNWI",
    new Date(Date.now() - 48 * 60 * 60 * 1000).toISOString(),
    "Excellent profile but hasn't responded to follow-up.",
    "introducer",
    "Savills Riyadh",
    "cash",
    "browsing",
    "9_12_months",
    "holiday_home"
  ),
];

// Generate daily metrics for last 14 days
const dates = generateDates(14);
export const demoDailyMetrics: DailyMetrics[] = dates.flatMap((date, index) => [
  {
    date,
    campaignId: "camp_1",
    leads: Math.floor(Math.random() * 8) + 3,
    spend: Math.floor(Math.random() * 50) + 60,
    impressions: Math.floor(Math.random() * 5000) + 8000,
    clicks: Math.floor(Math.random() * 200) + 150,
  },
]);

// Default Settings
export const defaultSettings: Settings = {
  orgName: "Naybourhood Demo",
  contactEmail: "demo@naybourhood.ai",
  metaPixelId: "",
  metaBusinessId: "",
  metaAdAccountId: "",
  metaPageId: "",
  metaAppId: "",
  metaAppSecret: "",
  metaAccessToken: "",
  crmWebhookUrl: "",
  csvFallbackEmail: "",
};

// Local storage keys
export const STORAGE_KEYS = {
  AUTH_TOKEN: "naybourhood_auth_token",
  USER: "naybourhood_user",
  CAMPAIGNS: "naybourhood_campaigns",
  LEADS: "naybourhood_leads",
  METRICS: "naybourhood_metrics",
  SETTINGS: "naybourhood_settings",
};

// Initialize demo data in localStorage if not present
export const initializeDemoData = () => {
  if (!localStorage.getItem(STORAGE_KEYS.CAMPAIGNS)) {
    localStorage.setItem(STORAGE_KEYS.CAMPAIGNS, JSON.stringify(demoCampaigns));
  }
  if (!localStorage.getItem(STORAGE_KEYS.LEADS)) {
    localStorage.setItem(STORAGE_KEYS.LEADS, JSON.stringify(demoLeads));
  }
  if (!localStorage.getItem(STORAGE_KEYS.METRICS)) {
    localStorage.setItem(STORAGE_KEYS.METRICS, JSON.stringify(demoDailyMetrics));
  }
  if (!localStorage.getItem(STORAGE_KEYS.SETTINGS)) {
    localStorage.setItem(STORAGE_KEYS.SETTINGS, JSON.stringify(defaultSettings));
  }
};
