// Demo data for large house builder (Developer) demonstration
// Company: "Horizon Homes" - a major UK residential developer

export const developerCompany = {
  name: "Horizon Homes",
  tagline: "Building Tomorrow's Communities",
  regions: ["London", "South East", "Midlands", "North West"],
};

// Developments (projects)
export const developerDevelopments = [
  {
    id: "dev_1",
    name: "Thames Gateway Village",
    location: "Woolwich, London",
    region: "London",
    priceRange: "£425,000 - £1,200,000",
    units: 450,
    unitsSold: 312,
    status: "live",
    image: "🏢",
    launchDate: "2024-03-15",
  },
  {
    id: "dev_2", 
    name: "Meridian Heights",
    location: "Stratford, London",
    region: "London",
    priceRange: "£380,000 - £850,000",
    units: 280,
    unitsSold: 195,
    status: "live",
    image: "🏗️",
    launchDate: "2024-06-01",
  },
  {
    id: "dev_3",
    name: "Parkside Quarter",
    location: "Reading, Berkshire",
    region: "South East",
    priceRange: "£295,000 - £620,000",
    units: 180,
    unitsSold: 98,
    status: "live",
    image: "🌳",
    launchDate: "2024-08-20",
  },
  {
    id: "dev_4",
    name: "Victoria Gardens",
    location: "Manchester City Centre",
    region: "North West",
    priceRange: "£220,000 - £485,000",
    units: 320,
    unitsSold: 245,
    status: "live",
    image: "🌺",
    launchDate: "2024-01-10",
  },
  {
    id: "dev_5",
    name: "Waterside Crescent",
    location: "Birmingham, Jewellery Quarter",
    region: "Midlands",
    priceRange: "£195,000 - £420,000",
    units: 150,
    unitsSold: 150,
    status: "sold-out",
    image: "✅",
    launchDate: "2023-06-15",
  },
  {
    id: "dev_6",
    name: "Kensington Place",
    location: "Kensington, London",
    region: "London",
    priceRange: "£1,500,000 - £4,500,000",
    units: 45,
    unitsSold: 12,
    status: "pre-launch",
    image: "💎",
    launchDate: "2025-03-01",
  },
];

// Demo campaigns for developer
// Results are calibrated to match actual leads per campaign
export const developerCampaigns = [
  // Thames Gateway Village campaigns (4 leads)
  {
    "Campaign Name": "Thames Gateway - Nigeria HNWI Q4",
    "Campaign name": "Thames Gateway - Nigeria HNWI Q4",
    "Amount spent (GBP)": 8500,
    Spend: 8500,
    Results: 1, // DEV001
    Impressions: 285000,
    Reach: 180000,
    Clicks: 4800,
    CTR: 1.68,
    CPC: 1.77,
    Platform: "Facebook",
    Status: "Active",
    "Reporting starts": "2024-10-01",
  },
  {
    "Campaign Name": "Thames Gateway - UAE Investors",
    "Campaign name": "Thames Gateway - UAE Investors",
    "Amount spent (GBP)": 6200,
    Spend: 6200,
    Results: 1, // DEV003
    Impressions: 195000,
    Reach: 125000,
    Clicks: 3200,
    CTR: 1.64,
    CPC: 1.94,
    Platform: "Instagram",
    Status: "Active",
    "Reporting starts": "2024-10-15",
  },
  {
    "Campaign Name": "Thames Gateway - UK First Time Buyers",
    "Campaign name": "Thames Gateway - UK First Time Buyers",
    "Amount spent (GBP)": 4800,
    Spend: 4800,
    Results: 2, // DEV005, DEV013
    Impressions: 420000,
    Reach: 280000,
    Clicks: 6800,
    CTR: 1.62,
    CPC: 0.71,
    Platform: "Facebook",
    Status: "Active",
    "Reporting starts": "2024-09-01",
  },
  // Meridian Heights campaigns (3 leads)
  {
    "Campaign Name": "Meridian Heights - Hong Kong Investors",
    "Campaign name": "Meridian Heights - Hong Kong Investors",
    "Amount spent (GBP)": 12500,
    Spend: 12500,
    Results: 3, // DEV002, DEV009, DEV014
    Impressions: 340000,
    Reach: 220000,
    Clicks: 5600,
    CTR: 1.65,
    CPC: 2.23,
    Platform: "Facebook",
    Status: "Active",
    "Reporting starts": "2024-09-15",
  },
  {
    "Campaign Name": "Meridian Heights - Singapore BTL",
    "Campaign name": "Meridian Heights - Singapore BTL",
    "Amount spent (GBP)": 5800,
    Spend: 5800,
    Results: 1, // DEV006
    Impressions: 145000,
    Reach: 95000,
    Clicks: 2400,
    CTR: 1.66,
    CPC: 2.42,
    Platform: "Instagram",
    Status: "Active",
    "Reporting starts": "2024-10-01",
  },
  // Parkside Quarter campaigns (2 leads)
  {
    "Campaign Name": "Parkside Quarter - Local Families",
    "Campaign name": "Parkside Quarter - Local Families",
    "Amount spent (GBP)": 3200,
    Spend: 3200,
    Results: 1, // DEV012
    Impressions: 280000,
    Reach: 185000,
    Clicks: 4200,
    CTR: 1.50,
    CPC: 0.76,
    Platform: "Facebook",
    Status: "Active",
    "Reporting starts": "2024-10-10",
  },
  {
    "Campaign Name": "Parkside Quarter - London Commuters",
    "Campaign name": "Parkside Quarter - London Commuters",
    "Amount spent (GBP)": 2800,
    Spend: 2800,
    Results: 1, // DEV004
    Impressions: 195000,
    Reach: 130000,
    Clicks: 3100,
    CTR: 1.59,
    CPC: 0.90,
    Platform: "Facebook",
    Status: "Active",
    "Reporting starts": "2024-10-20",
  },
  // Victoria Gardens campaigns (3 leads)
  {
    "Campaign Name": "Victoria Gardens - Manchester Professionals",
    "Campaign name": "Victoria Gardens - Manchester Professionals",
    "Amount spent (GBP)": 4500,
    Spend: 4500,
    Results: 2, // DEV007, DEV015
    Impressions: 380000,
    Reach: 250000,
    Clicks: 5800,
    CTR: 1.53,
    CPC: 0.78,
    Platform: "Facebook",
    Status: "Active",
    "Reporting starts": "2024-09-01",
  },
  {
    "Campaign Name": "Victoria Gardens - BTL Investors UK",
    "Campaign name": "Victoria Gardens - BTL Investors UK",
    "Amount spent (GBP)": 3800,
    Spend: 3800,
    Results: 1, // DEV008
    Impressions: 165000,
    Reach: 110000,
    Clicks: 2800,
    CTR: 1.70,
    CPC: 1.36,
    Platform: "Instagram",
    Status: "Active",
    "Reporting starts": "2024-10-05",
  },
  // Kensington Place campaigns (2 leads)
  {
    "Campaign Name": "Kensington Place - UHNWI Global",
    "Campaign name": "Kensington Place - UHNWI Global",
    "Amount spent (GBP)": 18500,
    Spend: 18500,
    Results: 1, // DEV010
    Impressions: 85000,
    Reach: 55000,
    Clicks: 1200,
    CTR: 1.41,
    CPC: 15.42,
    Platform: "Facebook",
    Status: "Active",
    "Reporting starts": "2024-11-01",
  },
  {
    "Campaign Name": "Kensington Place - Middle East VIP",
    "Campaign name": "Kensington Place - Middle East VIP",
    "Amount spent (GBP)": 15200,
    Spend: 15200,
    Results: 1, // DEV011
    Impressions: 62000,
    Reach: 40000,
    Clicks: 890,
    CTR: 1.44,
    CPC: 17.08,
    Platform: "Instagram",
    Status: "Active",
    "Reporting starts": "2024-11-10",
  },
];

// Demo leads for developer
export const developerLeads = [
  // Hot leads - High intent, viewing/offer stage
  {
    "Lead ID": "DEV001",
    "Name": "Chukwuemeka Obi",
    "Email": "c.obi@corporate.ng",
    "Phone Number": "+234 803 456 7890",
    "Country": "Nigeria",
    "Budget Range": "£800,000 - £1,200,000",
    "Preferred Bedrooms": "3 bed",
    "Timeline to Purchase": "Within 28 days",
    "Status": "Viewing Booked",
    "Source Platform": "Facebook",
    "Campaign": "Thames Gateway - Nigeria HNWI Q4",
    "Development": "Thames Gateway Village",
    "Date Added": new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    "Buyer Summary": "CEO of tech startup, relocating family to London. Cash buyer, very motivated.",
    "Cash/Mortgage": "Cash",
    "Are you ready to purchase within 28 days?": "Yes",
  },
  {
    "Lead ID": "DEV002",
    "Name": "Sarah Chen-Williams",
    "Email": "sarah.cw@investment.hk",
    "Phone Number": "+852 9876 5432",
    "Country": "Hong Kong",
    "Budget Range": "£600,000 - £850,000",
    "Preferred Bedrooms": "2 bed",
    "Timeline to Purchase": "Within 28 days",
    "Status": "Offer Made",
    "Source Platform": "Instagram",
    "Campaign": "Meridian Heights - Hong Kong Investors",
    "Development": "Meridian Heights",
    "Date Added": new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    "Buyer Summary": "Portfolio investor, owns 4 UK properties. Made offer £720,000 for unit 1204.",
    "Cash/Mortgage": "Cash",
    "Are you ready to purchase within 28 days?": "Yes",
  },
  {
    "Lead ID": "DEV003",
    "Name": "Mohammed Al-Rashid",
    "Email": "m.alrashid@emirates.ae",
    "Phone Number": "+971 50 123 4567",
    "Country": "UAE",
    "Budget Range": "£1,000,000 - £1,500,000",
    "Preferred Bedrooms": "Penthouse",
    "Timeline to Purchase": "0-3 months",
    "Status": "Viewing Booked",
    "Source Platform": "Facebook",
    "Campaign": "Thames Gateway - UAE Investors",
    "Development": "Thames Gateway Village",
    "Date Added": new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    "Buyer Summary": "Family office representative, looking for 2-3 units as investment portfolio.",
    "Cash/Mortgage": "Cash",
    "Are you ready to purchase within 28 days?": "Yes",
  },
  // Quality leads - Engaged, high quality
  {
    "Lead ID": "DEV004",
    "Name": "James Mitchell",
    "Email": "j.mitchell@solicitors.co.uk",
    "Phone Number": "+44 7700 900123",
    "Country": "United Kingdom",
    "Budget Range": "£320,000 - £400,000",
    "Preferred Bedrooms": "2 bed",
    "Timeline to Purchase": "0-3 months",
    "Status": "Contacted",
    "Source Platform": "Facebook",
    "Campaign": "Parkside Quarter - London Commuters",
    "Development": "Parkside Quarter",
    "Date Added": new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    "Buyer Summary": "Solicitor in London, looking to buy first home closer to Reading. Pre-approved mortgage.",
    "Cash/Mortgage": "Mortgage",
    "Are you ready to purchase within 28 days?": "No",
  },
  {
    "Lead ID": "DEV005",
    "Name": "Emma Thompson",
    "Email": "emma.t@nhs.net",
    "Phone Number": "+44 7890 234567",
    "Country": "United Kingdom",
    "Budget Range": "£380,000 - £450,000",
    "Preferred Bedrooms": "2 bed",
    "Timeline to Purchase": "0-3 months",
    "Status": "Engaged",
    "Source Platform": "Facebook",
    "Campaign": "Thames Gateway - UK First Time Buyers",
    "Development": "Thames Gateway Village",
    "Date Added": new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    "Buyer Summary": "NHS consultant, using Help to Buy. Very interested in 2-bed with balcony.",
    "Cash/Mortgage": "Mortgage",
    "Are you ready to purchase within 28 days?": "No",
  },
  {
    "Lead ID": "DEV006",
    "Name": "David Tan",
    "Email": "david.tan@tech.sg",
    "Phone Number": "+65 9123 4567",
    "Country": "Singapore",
    "Budget Range": "£500,000 - £700,000",
    "Preferred Bedrooms": "2-3 bed",
    "Timeline to Purchase": "0-3 months",
    "Status": "Contacted",
    "Source Platform": "Instagram",
    "Campaign": "Meridian Heights - Singapore BTL",
    "Development": "Meridian Heights",
    "Date Added": new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
    "Buyer Summary": "Tech executive, expanding UK property portfolio. Looking for BTL opportunity.",
    "Cash/Mortgage": "Cash",
    "Are you ready to purchase within 28 days?": "No",
  },
  // Medium leads - New, browsing
  {
    "Lead ID": "DEV007",
    "Name": "Olivia Johnson",
    "Email": "olivia.j@gmail.com",
    "Phone Number": "+44 7555 123456",
    "Country": "United Kingdom",
    "Budget Range": "£220,000 - £280,000",
    "Preferred Bedrooms": "1-2 bed",
    "Timeline to Purchase": "3-6 months",
    "Status": "New",
    "Source Platform": "Facebook",
    "Campaign": "Victoria Gardens - Manchester Professionals",
    "Development": "Victoria Gardens",
    "Date Added": new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
    "Buyer Summary": "Marketing manager in Manchester, first-time buyer exploring options.",
    "Cash/Mortgage": "Mortgage",
    "Are you ready to purchase within 28 days?": "No",
  },
  {
    "Lead ID": "DEV008",
    "Name": "Michael O'Brien",
    "Email": "m.obrien@finance.ie",
    "Phone Number": "+353 87 123 4567",
    "Country": "Ireland",
    "Budget Range": "£350,000 - £450,000",
    "Preferred Bedrooms": "2 bed",
    "Timeline to Purchase": "3-6 months",
    "Status": "New",
    "Source Platform": "Facebook",
    "Campaign": "Victoria Gardens - BTL Investors UK",
    "Development": "Victoria Gardens",
    "Date Added": new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    "Buyer Summary": "Irish investor looking at Manchester market for BTL.",
    "Cash/Mortgage": "Cash",
    "Are you ready to purchase within 28 days?": "No",
  },
  {
    "Lead ID": "DEV009",
    "Name": "Priya Sharma",
    "Email": "priya.s@corporate.in",
    "Phone Number": "+91 98765 43210",
    "Country": "India",
    "Budget Range": "£600,000 - £900,000",
    "Preferred Bedrooms": "3 bed",
    "Timeline to Purchase": "6-9 months",
    "Status": "New",
    "Source Platform": "Facebook",
    "Campaign": "Meridian Heights - Hong Kong Investors",
    "Development": "Meridian Heights",
    "Date Added": new Date(Date.now() - 12 * 24 * 60 * 60 * 1000).toISOString(),
    "Buyer Summary": "IT director, relocating to London in 2025. Looking for family home.",
    "Cash/Mortgage": "Mortgage",
    "Are you ready to purchase within 28 days?": "No",
  },
  // Luxury segment
  {
    "Lead ID": "DEV010",
    "Name": "Sheikh Abdullah Al-Maktoum",
    "Email": "office@almaktoum.ae",
    "Phone Number": "+971 4 123 4567",
    "Country": "UAE",
    "Budget Range": "£3,000,000+",
    "Preferred Bedrooms": "Penthouse",
    "Timeline to Purchase": "0-3 months",
    "Status": "Contacted",
    "Source Platform": "Facebook",
    "Campaign": "Kensington Place - UHNWI Global",
    "Development": "Kensington Place",
    "Date Added": new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    "Buyer Summary": "UHNWI, interested in full-floor penthouse. Family office handling.",
    "Cash/Mortgage": "Cash",
    "Are you ready to purchase within 28 days?": "Yes",
  },
  {
    "Lead ID": "DEV011",
    "Name": "Victoria Rothschild",
    "Email": "v.rothschild@family.ch",
    "Phone Number": "+41 22 123 4567",
    "Country": "Switzerland",
    "Budget Range": "£2,500,000 - £4,000,000",
    "Preferred Bedrooms": "3-4 bed",
    "Timeline to Purchase": "0-3 months",
    "Status": "New",
    "Source Platform": "Instagram",
    "Campaign": "Kensington Place - Middle East VIP",
    "Development": "Kensington Place",
    "Date Added": new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    "Buyer Summary": "Swiss family looking for London pied-à-terre. Very private, prefer discreet viewings.",
    "Cash/Mortgage": "Cash",
    "Are you ready to purchase within 28 days?": "No",
  },
  // More UK buyers
  {
    "Lead ID": "DEV012",
    "Name": "Sophie Anderson",
    "Email": "sophie.a@outlook.com",
    "Phone Number": "+44 7777 888999",
    "Country": "United Kingdom",
    "Budget Range": "£280,000 - £350,000",
    "Preferred Bedrooms": "2 bed",
    "Timeline to Purchase": "0-3 months",
    "Status": "Engaged",
    "Source Platform": "Facebook",
    "Campaign": "Parkside Quarter - Local Families",
    "Development": "Parkside Quarter",
    "Date Added": new Date(Date.now() - 9 * 24 * 60 * 60 * 1000).toISOString(),
    "Buyer Summary": "Young family, expecting first child. Looking for 2-bed with good schools nearby.",
    "Cash/Mortgage": "Mortgage",
    "Are you ready to purchase within 28 days?": "No",
  },
  {
    "Lead ID": "DEV013",
    "Name": "Robert Williams",
    "Email": "r.williams@pension.co.uk",
    "Phone Number": "+44 7123 456789",
    "Country": "United Kingdom",
    "Budget Range": "£400,000 - £550,000",
    "Preferred Bedrooms": "2 bed",
    "Timeline to Purchase": "Within 28 days",
    "Status": "Viewing Booked",
    "Source Platform": "Facebook",
    "Campaign": "Thames Gateway - UK First Time Buyers",
    "Development": "Thames Gateway Village",
    "Date Added": new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    "Buyer Summary": "Downsizer, selling Surrey home. Cash buyer, motivated to complete quickly.",
    "Cash/Mortgage": "Cash",
    "Are you ready to purchase within 28 days?": "Yes",
  },
  {
    "Lead ID": "DEV014",
    "Name": "Lucy Chen",
    "Email": "lucy.chen@bank.uk",
    "Phone Number": "+44 7999 111222",
    "Country": "United Kingdom",
    "Budget Range": "£500,000 - £650,000",
    "Preferred Bedrooms": "2-3 bed",
    "Timeline to Purchase": "0-3 months",
    "Status": "Contacted",
    "Source Platform": "Instagram",
    "Campaign": "Meridian Heights - Hong Kong Investors",
    "Development": "Meridian Heights",
    "Date Added": new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
    "Buyer Summary": "Investment banker, British-Chinese. Looking for modern apartment near work.",
    "Cash/Mortgage": "Mortgage",
    "Are you ready to purchase within 28 days?": "No",
  },
  {
    "Lead ID": "DEV015",
    "Name": "Thomas Baker",
    "Email": "t.baker@property.uk",
    "Phone Number": "+44 7444 555666",
    "Country": "United Kingdom",
    "Budget Range": "£240,000 - £320,000",
    "Preferred Bedrooms": "2 bed",
    "Timeline to Purchase": "3-6 months",
    "Status": "New",
    "Source Platform": "Facebook",
    "Campaign": "Victoria Gardens - Manchester Professionals",
    "Development": "Victoria Gardens",
    "Date Added": new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
    "Buyer Summary": "Property developer looking at BTL portfolio expansion in Manchester.",
    "Cash/Mortgage": "Cash",
    "Are you ready to purchase within 28 days?": "No",
  },
];

// Calculate summary stats
export const getDeveloperStats = () => {
  const totalLeads = developerLeads.length;
  const hotLeads = developerLeads.filter(l => 
    l.Status.includes('Viewing') || l.Status.includes('Offer')
  ).length;
  
  const totalSpend = developerCampaigns.reduce((sum, c) => sum + (c.Spend || 0), 0);
  const totalResults = developerCampaigns.reduce((sum, c) => sum + (c.Results || 0), 0);
  const avgCPL = totalResults > 0 ? totalSpend / totalResults : 0;
  
  const viewingsBooked = developerLeads.filter(l => l.Status.includes('Viewing')).length;
  const offersReceived = developerLeads.filter(l => l.Status.includes('Offer')).length;
  
  return {
    totalLeads,
    hotLeads,
    totalSpend,
    avgCPL,
    viewingsBooked,
    offersReceived,
    totalDevelopments: developerDevelopments.filter(d => d.status === 'live').length,
    totalUnits: developerDevelopments.reduce((sum, d) => sum + d.units, 0),
    unitsSold: developerDevelopments.reduce((sum, d) => sum + d.unitsSold, 0),
  };
};
