import type { Lead, TimelineEvent } from './types';

const daysAgo = (d: number) => new Date(Date.now() - d * 86400000).toISOString();

function buildTimeline(events: Array<Partial<TimelineEvent> & { type: TimelineEvent['type']; daysAgo: number; label: string; scoreAfter?: number; scoreDelta?: number; detail?: string }>): TimelineEvent[] {
  return events
    .map((e, i) => ({
      id: `evt_${i}`,
      at: daysAgo(e.daysAgo),
      type: e.type,
      label: e.label,
      detail: e.detail,
      scoreAfter: e.scoreAfter,
      scoreDelta: e.scoreDelta,
    }))
    .sort((a, b) => new Date(a.at).getTime() - new Date(b.at).getTime());
}

export const demoLeads: Lead[] = [
  {
    id: 'nb_001',
    full_name: 'James Whitfield',
    email: 'james.whitfield@protonmail.com',
    phone: '+447700900111',
    postcode: 'SW3 2AB',
    address: '14 Cheyne Walk, Chelsea, London',
    country: 'UK',
    property_name: 'The Chelsea Residences — Plot 12',
    asking_price: 1850000,
    budget: 2000000,
    buyer_status: 'homemover',
    selling_status: 'sold_stc',
    purchase_purpose: 'home',
    timeline_to_buy: 'now',
    payment_method: 'cash',
    aip_confirmed: false,
    funds_available: true,
    deposit_ready: true,
    broker_engaged: false,
    chain_status: 'no_chain',
    viewing_booked: true,
    whatsapp_replied: true,
    qualification_complete: true,
    call_logged: true,
    response_speed: 'fast',
    last_contact_at: daysAgo(1),
    source: 'Meta Ads',
    campaign: 'Chelsea HNWI Q2',
    assigned_agent: 'Sarah Bennett',
    email_valid: true,
    phone_valid: true,
    identity_confidence: 'high',
    linkedin_url: 'https://linkedin.com/in/jameswhitfield',
    employer: 'Whitfield Capital Partners',
    companies_house_match: 'Director x2 — active',
    initial_score: 58,
    timeline: buildTimeline([
      { daysAgo: 14, type: 'enquiry', label: 'Enquiry submitted', scoreAfter: 58 },
      { daysAgo: 14, type: 'whatsapp_sent', label: 'Welcome WhatsApp sent' },
      { daysAgo: 13, type: 'whatsapp_replied', label: 'Replied to WhatsApp', scoreDelta: 4, scoreAfter: 62 },
      { daysAgo: 10, type: 'qualification_complete', label: 'Qualification flow completed', scoreDelta: 6, scoreAfter: 68 },
      { daysAgo: 8, type: 'call', label: 'Call with agent', detail: 'Confirmed cash purchase, sold STC.', scoreDelta: 6, scoreAfter: 74 },
      { daysAgo: 5, type: 'funds_confirmed', label: 'Funds confirmed', scoreDelta: 5, scoreAfter: 79 },
      { daysAgo: 3, type: 'viewing_booked', label: 'Viewing booked', scoreDelta: 9, scoreAfter: 88 },
    ]),
  },
  {
    id: 'nb_002',
    full_name: 'Priya Shah',
    email: 'priya.shah@gmail.com',
    phone: '+447700900222',
    postcode: 'E14 5AB',
    address: '8 Marsh Wall, Canary Wharf, London',
    country: 'UK',
    property_name: 'Riverside Tower — 2 Bed',
    asking_price: 720000,
    budget: 700000,
    buyer_status: 'ftb',
    selling_status: 'na',
    purchase_purpose: 'home',
    timeline_to_buy: '0_3',
    payment_method: 'mortgage',
    aip_confirmed: true,
    funds_available: false,
    deposit_ready: true,
    broker_engaged: true,
    chain_status: 'no_chain',
    viewing_booked: true,
    whatsapp_replied: true,
    qualification_complete: true,
    call_logged: true,
    response_speed: 'fast',
    last_contact_at: daysAgo(2),
    source: 'Rightmove',
    campaign: 'Canary Wharf FTB',
    assigned_agent: 'Daniel Ng',
    email_valid: true, phone_valid: true, identity_confidence: 'high',
    employer: 'Deloitte UK',
    initial_score: 62,
    timeline: buildTimeline([
      { daysAgo: 9, type: 'enquiry', label: 'Enquiry submitted', scoreAfter: 62 },
      { daysAgo: 9, type: 'whatsapp_replied', label: 'Replied to WhatsApp', scoreDelta: 4, scoreAfter: 66 },
      { daysAgo: 7, type: 'qualification_complete', label: 'Qualification complete', scoreDelta: 5, scoreAfter: 71 },
      { daysAgo: 5, type: 'aip_confirmed', label: 'AIP confirmed', scoreDelta: 5, scoreAfter: 76 },
      { daysAgo: 2, type: 'viewing_booked', label: 'Viewing booked', scoreDelta: 5, scoreAfter: 81 },
    ]),
  },
  {
    id: 'nb_003',
    full_name: 'Mohammed Al-Rashid',
    email: 'm.rashid@outlook.com',
    phone: '+971501234567',
    postcode: 'W1K 6JP',
    address: 'Park Lane, Mayfair, London',
    country: 'UAE',
    property_name: 'Mayfair Penthouse Collection',
    asking_price: 4200000,
    budget: 5000000,
    buyer_status: 'investor',
    selling_status: 'na',
    purchase_purpose: 'investment',
    timeline_to_buy: 'now',
    payment_method: 'cash',
    aip_confirmed: false,
    funds_available: true,
    deposit_ready: true,
    broker_engaged: false,
    chain_status: 'no_chain',
    viewing_booked: false,
    whatsapp_replied: true,
    qualification_complete: true,
    call_logged: true,
    response_speed: 'fast',
    last_contact_at: daysAgo(1),
    source: 'Direct Website',
    campaign: 'Mayfair Investor',
    assigned_agent: 'Olivia Hart',
    email_valid: true, phone_valid: true, identity_confidence: 'high',
    companies_house_match: 'No UK directorships',
    initial_score: 60,
    timeline: buildTimeline([
      { daysAgo: 6, type: 'enquiry', label: 'Enquiry submitted', scoreAfter: 60 },
      { daysAgo: 5, type: 'whatsapp_replied', label: 'Replied to WhatsApp', scoreDelta: 4, scoreAfter: 64 },
      { daysAgo: 4, type: 'qualification_complete', label: 'Qualification complete', scoreDelta: 6, scoreAfter: 70 },
      { daysAgo: 1, type: 'call', label: 'Call confirmed funds', scoreDelta: 9, scoreAfter: 79 },
    ]),
  },
  {
    id: 'nb_004',
    full_name: 'Emma Thompson',
    email: 'emma.t@yahoo.co.uk',
    phone: '+447700900444',
    postcode: 'M1 3AA',
    address: '22 Deansgate, Manchester',
    country: 'UK',
    property_name: 'Deansgate Square — 1 Bed',
    asking_price: 320000,
    budget: 295000,
    buyer_status: 'ftb',
    selling_status: 'na',
    purchase_purpose: 'home',
    timeline_to_buy: '3_6',
    payment_method: 'mortgage',
    aip_confirmed: false,
    funds_available: false,
    deposit_ready: false,
    broker_engaged: false,
    chain_status: 'no_chain',
    viewing_booked: false,
    whatsapp_replied: true,
    qualification_complete: false,
    call_logged: false,
    response_speed: 'normal',
    last_contact_at: daysAgo(4),
    source: 'Zoopla',
    campaign: 'Manchester FTB',
    assigned_agent: 'Daniel Ng',
    email_valid: true, phone_valid: true, identity_confidence: 'medium',
    initial_score: 50,
    timeline: buildTimeline([
      { daysAgo: 12, type: 'enquiry', label: 'Enquiry submitted', scoreAfter: 50 },
      { daysAgo: 11, type: 'whatsapp_sent', label: 'Welcome WhatsApp sent' },
      { daysAgo: 10, type: 'whatsapp_replied', label: 'Replied to WhatsApp', scoreDelta: 4, scoreAfter: 54 },
    ]),
  },
  {
    id: 'nb_005',
    full_name: 'Robert Davies',
    email: 'r.davies@bt-internet.com',
    phone: '+447700900555',
    postcode: 'GU1 3AA',
    address: '5 High Street, Guildford',
    country: 'UK',
    property_name: 'Guildford Park — 4 Bed Detached',
    asking_price: 980000,
    budget: 950000,
    buyer_status: 'homemover',
    selling_status: 'on_market',
    purchase_purpose: 'home',
    timeline_to_buy: '3_6',
    payment_method: 'mortgage',
    aip_confirmed: true,
    funds_available: false,
    deposit_ready: true,
    broker_engaged: true,
    chain_status: 'in_chain',
    viewing_booked: true,
    whatsapp_replied: true,
    qualification_complete: true,
    call_logged: true,
    response_speed: 'normal',
    last_contact_at: daysAgo(3),
    source: 'OnTheMarket',
    campaign: 'Surrey Family Homes',
    assigned_agent: 'Sarah Bennett',
    email_valid: true, phone_valid: true, identity_confidence: 'high',
    initial_score: 55,
    timeline: buildTimeline([
      { daysAgo: 18, type: 'enquiry', label: 'Enquiry submitted', scoreAfter: 55 },
      { daysAgo: 16, type: 'qualification_complete', label: 'Qualification complete', scoreDelta: 5, scoreAfter: 60 },
      { daysAgo: 12, type: 'aip_confirmed', label: 'AIP confirmed', scoreDelta: 5, scoreAfter: 65 },
      { daysAgo: 6, type: 'viewing_booked', label: 'Viewing booked', scoreDelta: 5, scoreAfter: 70 },
      { daysAgo: 3, type: 'note', label: 'Chain risk noted', detail: 'Buyer property still on market' },
    ]),
  },
  {
    id: 'nb_006',
    full_name: 'Sophie Williams',
    email: 'sophie.w@hotmail.com',
    phone: '+447700900666',
    postcode: 'BS1 4DJ',
    address: '12 Queen Square, Bristol',
    country: 'UK',
    property_name: 'Harbourside Lofts — 2 Bed',
    asking_price: 410000,
    budget: 380000,
    buyer_status: 'ftb',
    selling_status: 'na',
    purchase_purpose: 'home',
    timeline_to_buy: '6_12',
    payment_method: 'mortgage',
    aip_confirmed: false,
    funds_available: false,
    deposit_ready: false,
    broker_engaged: false,
    chain_status: 'no_chain',
    viewing_booked: false,
    whatsapp_replied: false,
    qualification_complete: false,
    call_logged: false,
    response_speed: 'none',
    last_contact_at: daysAgo(11),
    source: 'Meta Ads',
    campaign: 'Bristol FTB Q2',
    assigned_agent: 'Olivia Hart',
    email_valid: true, phone_valid: true, identity_confidence: 'medium',
    initial_score: 42,
    timeline: buildTimeline([
      { daysAgo: 11, type: 'enquiry', label: 'Enquiry submitted', scoreAfter: 42 },
      { daysAgo: 11, type: 'whatsapp_sent', label: 'Welcome WhatsApp sent' },
    ]),
  },
  {
    id: 'nb_007',
    full_name: 'David Okonkwo',
    email: 'david.okonkwo@gmail.com',
    phone: '+2348012345678',
    postcode: 'NW8 7HY',
    address: 'St John\'s Wood, London',
    country: 'Nigeria',
    property_name: "St John's Wood Mansion Block",
    asking_price: 1650000,
    budget: 1700000,
    buyer_status: 'investor',
    selling_status: 'na',
    purchase_purpose: 'dependent',
    timeline_to_buy: '0_3',
    payment_method: 'cash',
    aip_confirmed: false,
    funds_available: true,
    deposit_ready: true,
    broker_engaged: false,
    chain_status: 'no_chain',
    viewing_booked: true,
    whatsapp_replied: true,
    qualification_complete: true,
    call_logged: false,
    response_speed: 'fast',
    last_contact_at: daysAgo(2),
    source: 'Introducer',
    campaign: 'International HNWI',
    assigned_agent: 'Olivia Hart',
    email_valid: true, phone_valid: true, identity_confidence: 'medium',
    initial_score: 56,
    timeline: buildTimeline([
      { daysAgo: 8, type: 'enquiry', label: 'Enquiry submitted', scoreAfter: 56 },
      { daysAgo: 7, type: 'qualification_complete', label: 'Qualification complete', scoreDelta: 6, scoreAfter: 62 },
      { daysAgo: 5, type: 'funds_confirmed', label: 'Funds confirmed', scoreDelta: 5, scoreAfter: 67 },
      { daysAgo: 2, type: 'viewing_booked', label: 'Viewing booked', scoreDelta: 5, scoreAfter: 72 },
    ]),
  },
  {
    id: 'nb_008',
    full_name: 'Helen Zhang',
    email: 'helen.zhang@invalid',
    phone: '+447700900888',
    postcode: '',
    address: '',
    country: 'UK',
    property_name: 'Battersea Power Station — Studio',
    asking_price: 540000,
    budget: 380000,
    buyer_status: 'browsing',
    selling_status: 'na',
    purchase_purpose: 'home',
    timeline_to_buy: 'unknown',
    payment_method: 'mortgage',
    aip_confirmed: false,
    funds_available: false,
    deposit_ready: false,
    broker_engaged: false,
    chain_status: 'unknown',
    viewing_booked: false,
    whatsapp_replied: false,
    qualification_complete: false,
    call_logged: false,
    response_speed: 'none',
    last_contact_at: daysAgo(15),
    source: 'Meta Ads',
    campaign: 'Battersea Studio',
    assigned_agent: 'Daniel Ng',
    email_valid: false, phone_valid: true, identity_confidence: 'low',
    initial_score: 28,
    timeline: buildTimeline([
      { daysAgo: 15, type: 'enquiry', label: 'Enquiry submitted', scoreAfter: 28 },
    ]),
  },
  {
    id: 'nb_009',
    full_name: 'Thomas Anderson',
    email: 'tom.anderson@gmail.com',
    phone: '+447700900999',
    postcode: 'EH1 1YZ',
    address: 'Royal Mile, Edinburgh',
    country: 'UK',
    property_name: 'New Town Townhouse',
    asking_price: 875000,
    budget: 900000,
    buyer_status: 'downsizer',
    selling_status: 'sold_stc',
    purchase_purpose: 'home',
    timeline_to_buy: 'now',
    payment_method: 'cash',
    aip_confirmed: false,
    funds_available: true,
    deposit_ready: true,
    broker_engaged: false,
    chain_status: 'no_chain',
    viewing_booked: true,
    whatsapp_replied: true,
    qualification_complete: true,
    call_logged: true,
    response_speed: 'fast',
    last_contact_at: daysAgo(1),
    source: 'CRM',
    campaign: 'Edinburgh Downsizer',
    assigned_agent: 'Sarah Bennett',
    email_valid: true, phone_valid: true, identity_confidence: 'high',
    initial_score: 64,
    timeline: buildTimeline([
      { daysAgo: 7, type: 'enquiry', label: 'Enquiry submitted', scoreAfter: 64 },
      { daysAgo: 6, type: 'qualification_complete', label: 'Qualification complete', scoreDelta: 6, scoreAfter: 70 },
      { daysAgo: 3, type: 'funds_confirmed', label: 'Funds confirmed', scoreDelta: 5, scoreAfter: 75 },
      { daysAgo: 1, type: 'viewing_booked', label: 'Viewing booked', scoreDelta: 9, scoreAfter: 84 },
    ]),
  },
  {
    id: 'nb_010',
    full_name: 'Aisha Mohammed',
    email: 'aisha.m@gmail.com',
    phone: '+447700901010',
    postcode: 'B1 1AA',
    address: '10 Bull Ring, Birmingham',
    country: 'UK',
    property_name: 'Birmingham Central — 2 Bed',
    asking_price: 285000,
    budget: 290000,
    buyer_status: 'investor',
    selling_status: 'na',
    purchase_purpose: 'investment',
    timeline_to_buy: '0_3',
    payment_method: 'mixed',
    aip_confirmed: true,
    funds_available: true,
    deposit_ready: true,
    broker_engaged: true,
    chain_status: 'no_chain',
    viewing_booked: false,
    whatsapp_replied: true,
    qualification_complete: true,
    call_logged: true,
    response_speed: 'normal',
    last_contact_at: daysAgo(2),
    source: 'Rightmove',
    campaign: 'BTL Investor',
    assigned_agent: 'Olivia Hart',
    email_valid: true, phone_valid: true, identity_confidence: 'high',
    employer: 'AM Property Holdings Ltd',
    companies_house_match: 'Director, AM Property Holdings Ltd',
    initial_score: 60,
    timeline: buildTimeline([
      { daysAgo: 10, type: 'enquiry', label: 'Enquiry submitted', scoreAfter: 60 },
      { daysAgo: 9, type: 'qualification_complete', label: 'Qualification complete', scoreDelta: 5, scoreAfter: 65 },
      { daysAgo: 6, type: 'aip_confirmed', label: 'AIP confirmed', scoreDelta: 5, scoreAfter: 70 },
      { daysAgo: 2, type: 'call', label: 'Discussed BTL strategy', scoreDelta: 3, scoreAfter: 73 },
    ]),
  },
  {
    id: 'nb_011',
    full_name: 'Oliver Brown',
    email: 'oliver.brown@gmail.com',
    phone: '+447700901111',
    postcode: 'OX1 2JD',
    address: 'High Street, Oxford',
    country: 'UK',
    property_name: 'Oxford Mews — 3 Bed',
    asking_price: 720000,
    budget: 600000,
    buyer_status: 'homemover',
    selling_status: 'on_market',
    purchase_purpose: 'home',
    timeline_to_buy: '6_12',
    payment_method: 'mortgage',
    aip_confirmed: false,
    funds_available: false,
    deposit_ready: false,
    broker_engaged: false,
    chain_status: 'needs_to_sell',
    viewing_booked: false,
    whatsapp_replied: true,
    qualification_complete: true,
    call_logged: false,
    response_speed: 'slow',
    last_contact_at: daysAgo(8),
    source: 'Zoopla',
    campaign: 'Oxford Family',
    assigned_agent: 'Daniel Ng',
    email_valid: true, phone_valid: true, identity_confidence: 'medium',
    initial_score: 48,
    timeline: buildTimeline([
      { daysAgo: 14, type: 'enquiry', label: 'Enquiry submitted', scoreAfter: 48 },
      { daysAgo: 12, type: 'qualification_complete', label: 'Qualification complete', scoreDelta: 4, scoreAfter: 52 },
    ]),
  },
  {
    id: 'nb_012',
    full_name: 'Fatima Hassan',
    email: 'fatima.h@gmail.com',
    phone: '+447700901212',
    postcode: 'LS1 4AP',
    address: 'Park Row, Leeds',
    country: 'UK',
    property_name: 'Leeds Dock — 1 Bed',
    asking_price: 215000,
    budget: 215000,
    buyer_status: 'ftb',
    selling_status: 'na',
    purchase_purpose: 'home',
    timeline_to_buy: 'now',
    payment_method: 'mortgage',
    aip_confirmed: true,
    funds_available: false,
    deposit_ready: true,
    broker_engaged: true,
    chain_status: 'no_chain',
    viewing_booked: true,
    whatsapp_replied: true,
    qualification_complete: true,
    call_logged: true,
    response_speed: 'fast',
    last_contact_at: daysAgo(1),
    source: 'Direct Website',
    campaign: 'Leeds FTB',
    assigned_agent: 'Sarah Bennett',
    email_valid: true, phone_valid: true, identity_confidence: 'high',
    initial_score: 65,
    timeline: buildTimeline([
      { daysAgo: 6, type: 'enquiry', label: 'Enquiry submitted', scoreAfter: 65 },
      { daysAgo: 5, type: 'qualification_complete', label: 'Qualification complete', scoreDelta: 5, scoreAfter: 70 },
      { daysAgo: 3, type: 'aip_confirmed', label: 'AIP confirmed', scoreDelta: 5, scoreAfter: 75 },
      { daysAgo: 1, type: 'viewing_booked', label: 'Viewing booked', scoreDelta: 7, scoreAfter: 82 },
    ]),
  },
  {
    id: 'nb_013',
    full_name: 'Christopher Lee',
    email: 'chris.lee@invalid-domain.xyz',
    phone: '+44770090',
    postcode: 'CB1 2AA',
    address: '',
    country: 'UK',
    property_name: 'Cambridge Riverside — Studio',
    asking_price: 295000,
    budget: 200000,
    buyer_status: 'browsing',
    selling_status: 'na',
    purchase_purpose: 'investment',
    timeline_to_buy: 'unknown',
    payment_method: 'mortgage',
    aip_confirmed: false,
    funds_available: false,
    deposit_ready: false,
    broker_engaged: false,
    chain_status: 'unknown',
    viewing_booked: false,
    whatsapp_replied: false,
    qualification_complete: false,
    call_logged: false,
    response_speed: 'none',
    last_contact_at: daysAgo(20),
    source: 'Meta Ads',
    campaign: 'Cambridge Studio',
    assigned_agent: 'Olivia Hart',
    email_valid: false, phone_valid: false, identity_confidence: 'low',
    initial_score: 22,
    timeline: buildTimeline([
      { daysAgo: 20, type: 'enquiry', label: 'Enquiry submitted', scoreAfter: 22 },
    ]),
  },
  {
    id: 'nb_014',
    full_name: 'Maria Garcia',
    email: 'maria.garcia@gmail.com',
    phone: '+447700901414',
    postcode: 'BN1 1AA',
    address: 'The Lanes, Brighton',
    country: 'UK',
    property_name: 'Brighton Marina — 2 Bed',
    asking_price: 450000,
    budget: 460000,
    buyer_status: 'investor',
    selling_status: 'na',
    purchase_purpose: 'holiday',
    timeline_to_buy: '0_3',
    payment_method: 'cash',
    aip_confirmed: false,
    funds_available: true,
    deposit_ready: true,
    broker_engaged: false,
    chain_status: 'no_chain',
    viewing_booked: false,
    whatsapp_replied: true,
    qualification_complete: true,
    call_logged: true,
    response_speed: 'normal',
    last_contact_at: daysAgo(3),
    source: 'Rightmove',
    campaign: 'Coastal Holiday',
    assigned_agent: 'Daniel Ng',
    email_valid: true, phone_valid: true, identity_confidence: 'high',
    initial_score: 58,
    timeline: buildTimeline([
      { daysAgo: 9, type: 'enquiry', label: 'Enquiry submitted', scoreAfter: 58 },
      { daysAgo: 8, type: 'qualification_complete', label: 'Qualification complete', scoreDelta: 5, scoreAfter: 63 },
      { daysAgo: 4, type: 'call', label: 'Call confirmed cash funds', scoreDelta: 6, scoreAfter: 69 },
    ]),
  },
  {
    id: 'nb_015',
    full_name: 'William Taylor',
    email: 'will.taylor@gmail.com',
    phone: '+447700901515',
    postcode: 'CF10 1AA',
    address: 'Cardiff Bay, Cardiff',
    country: 'UK',
    property_name: 'Cardiff Bay Heights — 3 Bed',
    asking_price: 395000,
    budget: 380000,
    buyer_status: 'homemover',
    selling_status: 'under_offer',
    purchase_purpose: 'home',
    timeline_to_buy: '0_3',
    payment_method: 'mortgage',
    aip_confirmed: true,
    funds_available: false,
    deposit_ready: true,
    broker_engaged: true,
    chain_status: 'in_chain',
    viewing_booked: true,
    whatsapp_replied: true,
    qualification_complete: true,
    call_logged: true,
    response_speed: 'fast',
    last_contact_at: daysAgo(2),
    source: 'OnTheMarket',
    campaign: 'Cardiff Family',
    assigned_agent: 'Sarah Bennett',
    email_valid: true, phone_valid: true, identity_confidence: 'high',
    initial_score: 60,
    timeline: buildTimeline([
      { daysAgo: 11, type: 'enquiry', label: 'Enquiry submitted', scoreAfter: 60 },
      { daysAgo: 10, type: 'qualification_complete', label: 'Qualification complete', scoreDelta: 5, scoreAfter: 65 },
      { daysAgo: 7, type: 'aip_confirmed', label: 'AIP confirmed', scoreDelta: 5, scoreAfter: 70 },
      { daysAgo: 4, type: 'note', label: 'Property went under offer', scoreDelta: 2, scoreAfter: 72 },
      { daysAgo: 2, type: 'viewing_booked', label: 'Viewing booked', scoreDelta: 5, scoreAfter: 77 },
    ]),
  },
];
